import { Bill, BillExplanation, Customer } from "./types";
import { inr } from "./billExplain";

// Client-side PDF generation. jsPDF is imported dynamically so it never lands
// in the server bundle.
export async function downloadBillPdf(
  customer: Customer,
  bill: Bill,
  explanation: BillExplanation
) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 40;
  let y = 48;

  const green: [number, number, number] = [5, 150, 105];
  const ink: [number, number, number] = [30, 41, 59];
  const slate: [number, number, number] = [100, 116, 139];

  // Header band
  doc.setFillColor(...green);
  doc.rect(0, 0, W, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...ink);
  doc.text("SuRaksha AI", M, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...slate);
  doc.text("Torrent Gas · PNG Tax Invoice", M, y + 15);
  doc.setFontSize(10);
  doc.setTextColor(...ink);
  doc.text(`Bill: ${bill.cycleLabel}`, W - M, y, { align: "right" });
  doc.setTextColor(...slate);
  doc.setFontSize(9);
  doc.text(`Status: ${bill.status.toUpperCase()}`, W - M, y + 15, { align: "right" });

  y += 40;
  doc.setDrawColor(226, 232, 240);
  doc.line(M, y, W - M, y);

  // Customer block
  y += 24;
  doc.setFontSize(9);
  doc.setTextColor(...slate);
  doc.text("BILLED TO", M, y);
  doc.text("CONNECTION", W / 2, y);
  y += 16;
  doc.setFontSize(11);
  doc.setTextColor(...ink);
  doc.setFont("helvetica", "bold");
  doc.text(customer.name, M, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...slate);
  doc.text(`A/C ${customer.accountNo}`, M, y + 14);
  doc.text(customer.area, M, y + 27);

  doc.text(`Meter: ${customer.meterNo ?? "-"}`, W / 2, y);
  doc.text(`Type: ${customer.type}`, W / 2, y + 14);
  doc.text(
    `Period: ${fmtDate(bill.periodStart)} – ${fmtDate(bill.periodEnd)}`,
    W / 2,
    y + 27
  );

  // Charges table
  y += 58;
  const rows: [string, string][] = [
    [`Gas consumption (${bill.unitsScm} SCM @ ${inr(bill.ratePerScm)}/SCM)`, inr(bill.gasCharge)],
    ["Fixed / service charge", inr(bill.fixedCharge)],
  ];
  if (bill.tax) rows.push(["Taxes", inr(bill.tax)]);
  if (bill.arrears) rows.push(["Arrears carried forward", inr(bill.arrears)]);

  doc.setFillColor(241, 245, 249);
  doc.rect(M, y, W - 2 * M, 22, "F");
  doc.setTextColor(...slate);
  doc.setFontSize(9);
  doc.text("DESCRIPTION", M + 10, y + 15);
  doc.text("AMOUNT", W - M - 10, y + 15, { align: "right" });
  y += 22;

  doc.setTextColor(...ink);
  doc.setFontSize(10);
  rows.forEach(([label, amt]) => {
    y += 22;
    doc.text(label, M + 10, y);
    doc.text(amt, W - M - 10, y, { align: "right" });
    doc.setDrawColor(241, 245, 249);
    doc.line(M, y + 8, W - M, y + 8);
  });

  y += 30;
  doc.setFillColor(...green);
  doc.rect(M, y, W - 2 * M, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("TOTAL PAYABLE", M + 10, y + 20);
  doc.text(inr(bill.amount), W - M - 10, y + 20, { align: "right" });
  if (bill.dueDate) {
    y += 44;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...slate);
    doc.text(`Due date: ${fmtDate(bill.dueDate)}`, M, y);
  }

  // AI explanation box
  y += 30;
  doc.setDrawColor(...green);
  doc.setFillColor(236, 253, 245);
  const boxH = 96;
  doc.roundedRect(M, y, W - 2 * M, boxH, 8, 8, "FD");
  doc.setTextColor(...green);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("SuRaksha AI · Why this amount", M + 12, y + 20);
  doc.setTextColor(...ink);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const lines = doc.splitTextToSize(explanation.narrative, W - 2 * M - 24);
  doc.text(lines, M + 12, y + 38);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...slate);
  doc.text(
    "Generated by SuRaksha AI · figures illustrative · not a legal tax document in this prototype.",
    M,
    doc.internal.pageSize.getHeight() - 30
  );

  doc.save(`${customer.accountNo}-${bill.cycleLabel.replace(/\s+/g, "_")}.pdf`);
}

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}
